apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  type: {{ .Values.service.type }}
