= Publishing Helm Charts
:stylesheet: boot-flatly.css
:nofooter:
:data-uri:
:icons: font
:linkattrs:

The DevOps team wants to


.. Package the helm charts to an archive
.. Create a repository using `ChartMuseum`
.. Publish the helm charts to `ChartMuseum`
.. Add dependencies to the parent & child charts in the umbrella chart

== Learning Outcomes
After completing the lab, you will be able to understand

• Packaging helm chart
• Publishing to helm chart repository
• Defining dependencies
• Tags and conditions


===  Refactoring the directory structure
. We need to move the charts to be archived

+
[source, shell script]
--------------
cd ~/workspace/helm-charts
helm package pages
helm repo index .
cat index.yaml
--------------

=== Install ChartMuseum
. ChartMuseum is an open-source `Helm Chart Repository server`.
We will install the `ChartMuseum` locally. However, this can also be accomplished for a production environment with additional configurations.
+
[source, shell script]
--------------
curl -LO https://s3.amazonaws.com/chartmuseum/release/latest/bin/linux/amd64/chartmuseum
chmod u+x chartmuseum
sudo mv chartmuseum /usr/local/bin
--------------

+
[source, shell script]
--------------
mkdir ~/helm
mkdir ~/helm/repo
chartmuseum --storage="local" --storage-local-rootdir=/home/student/helm/repo
--------------

=== Publish

. Let's publish the chart archives to the ChartMuseum repository server

+
[source, shell script]
-------------
cp *.tgz  ~/helm/repo
curl http://localhost:8080/api/charts | jq .
-------------


=== Fetching the published charts from ChartMuseum
. Configure Helm to use ChartMuseum repository

+
[source, shell script]
--------------
helm repo add chartmuseum http://localhost:8080
helm repo list
helm repo update
helm search repo chartmuseum/
--------------

. Create a new directory and Chart.yaml to test the published chart

+
[source, shell script]
--------------
mkdir ~/workspace/helm-charts/pages-package
cd ~/workspace/helm-charts/pages-package
touch Chart.yaml
--------------

+
`pages-package/Chart.yaml`

+
[source, yaml]
--------------
apiVersion: v2
name: pages
description: A Helm chart for Pages Application
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: pages
    version: 1.0.0
    repository: http://localhost:8080
--------------


. Downloading published charts from the repo

+
[source, shell script]
--------------
cd ~/workspace/helm-charts/pages-package
helm dependency update .
ls
helm dependency list .
helm dependency build .
--------------



